spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heart-signal-database?serverTimezone=Asia/Seoul
    username: heart-signal-admin
    password: heart-signal-admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
  flyway:
    user: heart-signal-admin
    password: heart-signal-admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: heart-signal-db

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5f08f6b3929d0013a8f484faa6b4fc3f
            client-secret: ozbZ2xyiHKXcpo36JDk3a2xRqmKS887r
            scope:
              - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secretKey: asdfasdfasdfasdrtqwetqpkna;pilugipk1j23k4lhj1adfkj9312kl3n@*!!~asdkflj9@#Nvlny.asdf

  access:
    expiration: 604800000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: ReAuthorization

redirect:
  url:
    userInfo: http://localhost:3000/userInfo
    main: http://localhost:3000/main