spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heartSignal_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: heart-signal-db
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 1

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5f08f6b3929d0013a8f484faa6b4fc3f
            client-secret: ozbZ2xyiHKXcpo36JDk3a2xRqmKS887r
            scope:
              - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  secretKey: asdfasdfasdfasdrtqwetqpkna;pilugipk1j23k4lhj1adfkj9312kl3n@*!!~asdkflj9@#Nvlny.asdf

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: ReAuthorization